spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/NTCTest?serverTimezone=UTC
    username: postgres
    password: 9999
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
